name: "Astro FTP"
on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a deployment
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git config crlf
        run: git config --global core.autocrlf false

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.4.x

      - name: PNPM Install
        shell: "bash"
        run: pnpm install

      - name: Build
        shell: "bash"
        run: pnpm run build

      - name: Upload to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          port: 21
          protocol: ftp
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /www/
          dry-run: false
          local-dir: ./dist/
          log-level: verbose
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/wp-content/**
